### ISSUE TITLE
Doesn't install on OS Sierra

### ISSUE THREAD

**Issue by DavidAwad** [gardaud/hack-exe#5]
```shell
$ pip install hack-exe
Collecting hack-exe
  Downloading hack-exe-0.2.tar.gz
Building wheels for collected packages: hack-exe
  Running setup.py bdist_wheel for hack-exe ... done
  Stored in directory: /Users/david/Library/Caches/pip/wheels/a5/91/4c/9ff8eb7e77e8e91f17f9ad28e0857f764301256152272ccd15
Successfully built hack-exe
Installing collected packages: hack-exe
Successfully installed hack-exe-0.2
$ hack.exe google.com
Traceback (most recent call last):
  File "/usr/local/bin/hack.exe", line 5, in <module>
    from hack_exe import main
ImportError: cannot import name 'main'
```

Looks like a small python problem. :

**Comment by gardaud** [comment]
Took me forever to look at this, sorry. 

Can't reproduce on 10.12.5. Can I get more info on your system + python installation?

**Comment by Yousanflics** [comment]
Hi I hack the same bug with upstairs and my python version is 3.6 and my pip is pip3 and version is 10.0.1 after installing when I try to run the code it shows this:
```
Traceback (most recent call last):
  File "/usr/local/bin/hack.exe", line 5, in <module>
    from hack_exe import main
ImportError: cannot import name 'main'
```
